apiVersion: v2
name: kproximate
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# Intentionally set to 0.0.0, this is set to the git tag when published
version: 0.3.0

# Intentionally set to 0.0.0, this is set to the git tag when published
appVersion: 0.3.0

dependencies:
